// 'use client'

// import { Box, Heading, Text, Link, ListItem } from "@chakra-ui/react";

// export default function PrivacyPolicyPage() {
//   return (
//     <>
//     <Box maxW="800px" mx="auto" px={4} py={8}>
//       <Heading as="h1" size="xl" mb={4}>
//         Privacy Policy
//       </Heading>

//       <Text mb={2}>Last updated: August 18, 2025</Text>

//       <Text mb={4}>
//         This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
//       </Text>

//       <Text mb={4}>
//         We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the{" "}
//         <Link href="https://www.termsfeed.com/privacy-policy-generator/" color="blue.500">
//           Privacy Policy Generator
//         </Link>.
//       </Text>

//       <Heading as="h2" size="lg" mt={6} mb={2}>Interpretation and Definitions</Heading>

//       <Heading as="h3" size="md" mt={4} mb={2}>Interpretation</Heading>
//       <Text mb={2}>
//         The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
//       </Text>

//       <Heading as="h3" size="md" mt={4} mb={2}>Definitions</Heading>
//       <Text mb={2}>For the purposes of this Privacy Policy:</Text>

//       <UnorderedList mb={4}>
//         <ListItem><Text><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</Text></ListItem>
//         <ListItem><Text><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</Text></ListItem>
//         <ListItem><Text><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Catardot.</Text></ListItem>
//         <ListItem><Text><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</Text></ListItem>
//         <ListItem><Text><strong>Country</strong> refers to: Indonesia</Text></ListItem>
//         <ListItem><Text><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</Text></ListItem>
//         <ListItem><Text><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</Text></ListItem>
//         <ListItem><Text><strong>Service</strong> refers to the Website.</Text></ListItem>
//         <ListItem><Text><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company...</Text></ListItem>
//         <ListItem><Text><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</Text></ListItem>
//         <ListItem><Text><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</Text></ListItem>
//         <ListItem><Text><strong>Website</strong> refers to Catardot, accessible from <Link href="https://catardot.vercel.app" isExternal color="blue.500">https://catardot.vercel.app</Link></Text></ListItem>
//         <ListItem><Text><strong>You</strong> means the individual accessing or using the Service...</Text></ListItem>
//       </UnorderedList>

//       {/* Bagian lain seperti "Collecting and Using Your Personal Data" juga bisa dikonversi dengan struktur yang sama */}
      
//       <Heading as="h2" size="lg" mt={6} mb={2}>Contact Us</Heading>
//       <Text mb={2}>If you have any questions about this Privacy Policy, You can contact us:</Text>
//       <UnorderedList>
//         <ListItem><Text>By email: ridhaarlian@proton.me</Text></ListItem>
//         <ListItem>
//           <Text>
//             By visiting this page on our website:{" "}
//             <Link href="https://catardot.vercel.app/contact" color="blue.500">
//               https://catardot.vercel.app/contact
//             </Link>
//           </Text>
//         </ListItem>
//       </UnorderedList>
//     </Box>
//     </>
//   )
// }
