import type { Metadata } from "next"
import { Toaster } from "@/components/ui/toaster"
import { Provider } from "@/components/ui/provider"
import { Playfair_Display, Merriweather, Quicksand } from "next/font/google"

const merriSans = Merriweather({
  variable: "--font-merri-sans",
  subsets: ["latin"],
  weight: "400"
})

const playSans = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"]
})

const quickSand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Catardot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${merriSans.variable} ${quickSand.variable} ${playSans.variable}`} >
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  )
}