import { defineTextStyles } from "@chakra-ui/react"

export const textStyles = defineTextStyles({
  headingLP:{
    description: "For Heading in Landing Page",
    value: {
      fontFamily: "var(--font-playfair-display)",
      fontWeight: "600",
      fontSize: { base: "50px", md: "50px" },
      lineHeight: "24px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  subHeadingLP:{
    description: "For Sub Heading in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "400",
      fontSize: "35px",
      lineHeight: "40px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  textLP:{
    description: "For Sub Heading in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "400",
      fontSize: "18px",
      lineHeight: "40px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  headLPGrid:{
    description: "For Heading Feature Grid in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "800",
      fontSize: "20px",
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "uppercase",
    },
  },
  textLPGrid:{
    description: "For Heading Feature Grid in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "500",
      fontSize: "16px",
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  headingLPLogin:{
    description: "For Heading Feature Grid in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "800",
      fontSize: "20px",
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  textLPLogin:{
    description: "For Heading Feature Grid in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "500",
      fontSize: "14px",
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  googleLPLogin:{
    description: "For Heading Feature Grid in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "500",
      fontSize: "14px",
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  miniHeadingLPFeat:{
    description: "For Heading Feature Grid in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "800",
      fontSize: "14px",
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "Uppercase",
    },
  },
  headingLPFeat:{
    description: "For Heading Feature Grid in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "800",
      fontSize: "16px",
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  textLPFeat:{
    description: "For Heading Feature Grid in Landing Page",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "500",
      fontSize: "12px",
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  headingNav:{
    description: "For Heading in Navbar",
    value: {
      fontFamily: "var(--font-playfair-display)",
      fontWeight: "600",
      fontSize: { base: "22px", sm: "16px", md: "16px", lg: "16px", xl: "40px" },
      lineHeight: "24px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  subheadingNav:{
    description: "For Sub Heading in Navbar",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "600",
      fontSize: { base: "14px", sm: "16px", md: "16px", lg: "16px", xl: "16px" },
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  selectNav:{
    description: "For Text Menu in Navbar",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "500",
      fontSize: { base: "14px", sm: "16px", md: "16px", lg: "16px", xl: "14px" },
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  timeWidgetNum:{
    description: "For Number in Time Widget",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "600",
      fontSize: { base: "14px", sm: "16px", md: "16px", lg: "16px", xl: "60px" },
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  timeWidgetText:{
    description: "For Text in Time Widget",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "600",
      fontSize: { base: "14px", sm: "16px", md: "16px", lg: "16px", xl: "35px" },
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  headingStatusWidget:{
    description: "For Text in Time Widget",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: { base: "600", sm: "600", md: "700", lg: "700", xl: "700" },
      fontSize: { base: "14px", sm: "14px", md: "16px", lg: "16px", xl: "16px" },
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  contentStatusWidget:{
    description: "For Text in Time Widget",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "600",
      fontSize: { base: "14px", sm: "16px", md: "16px", lg: "16px", xl: "14px" },
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  infoStatusWidget:{
    description: "For Text in Time Widget",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "600",
      fontSize: { base: "12px", sm: "12px", md: "16px", lg: "16px", xl: "14px" },
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
  floatingButtonText:{
    description: "For Text in FAB",
    value: {
      fontFamily: "var(--font-quicksand)",
      fontWeight: "600",
      fontSize: { base: "14px", sm: "12px", md: "16px", lg: "16px", xl: "14px" },
      lineHeight: "20px",
      letterSpacing: "0px",
      textDecoration: "none",
      textTransform: "none",
    },
  },
})