import { defineTextStyles } from '@chakra-ui/react'

export const textStyles = defineTextStyles({
  headingLP:{
    description: 'For Heading in Landing Page',
    value: {
      fontFamily: 'var(--font-playfair-display)',
      fontWeight: '600',
      fontSize: { base: '50px', md: '50px' },
      lineHeight: '24px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'none',
    },
  },
  subHeadingLP:{
    description: 'For Sub Heading in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '400',
      fontSize: '35px',
      lineHeight: '40px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'none',
    },
  },
  textLP:{
    description: 'For Sub Heading in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '400',
      fontSize: '18px',
      lineHeight: '40px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'none',
    },
  },
  headLPGrid:{
    description: 'For Heading Feature Grid in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '800',
      fontSize: '20px',
      lineHeight: '20px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'none',
    },
  },
  textLPGrid:{
    description: 'For Heading Feature Grid in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '500',
      fontSize: '16px',
      lineHeight: '20px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'none',
    },
  },
  headingLPLogin:{
    description: 'For Heading Feature Grid in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '800',
      fontSize: '20px',
      lineHeight: '20px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'none',
    },
  },
  textLPLogin:{
    description: 'For Heading Feature Grid in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '500',
      fontSize: '14px',
      lineHeight: '20px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'none',
    },
  },
  googleLPLogin:{
    description: 'For Heading Feature Grid in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '500',
      fontSize: '14px',
      lineHeight: '20px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'none',
    },
  },
  miniHeadingLPFeat:{
    description: 'For Heading Feature Grid in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '800',
      fontSize: '14px',
      lineHeight: '20px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: 'Uppercase',
    },
  },
  headingLPFeat:{
    description: 'For Heading Feature Grid in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '800',
      fontSize: '16px',
      lineHeight: '20px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: '',
    },
  },
  textLPFeat:{
    description: 'For Heading Feature Grid in Landing Page',
    value: {
      fontFamily: 'var(--font-quicksand)',
      fontWeight: '500',
      fontSize: '12px',
      lineHeight: '20px',
      letterSpacing: '0px',
      textDecoration: 'none',
      textTransform: '',
    },
  },
})