export const PROMPT = [
  // `Hari ini hal kecil apa yang paling berkesan?`,
  // `Siapa yang membuatmu tersenyum hari ini?`,
  // `Apa momen paling lucu hari ini?`,
  // `Hal baru apa yang kamu sadari hari ini?`,
  // `Apa hal sederhana yang kamu syukuri hari ini?`,
  // `Kalau ada satu hal yang ingin kamu ulang dari hari ini, apa itu?`,
  // `Apa satu kejadian yang membuatmu berpikir?`,
  // `Apa yang kamu lihat di jalan yang menarik perhatian?`,
  // `Apa percakapan paling menyenangkan hari ini?`,
  // `Ada suara atau lagu apa yang mengisi harimu?`,
  // `Apa aroma atau makanan yang kamu nikmati hari ini?`,
  // `Hal kecil apa yang bikin kamu merasa damai?`,
  // `Apa kejadian kecil yang bikin kamu kesal tapi lucu?`,
  // `Siapa yang kamu temui hari ini dan mengesankan?`,
  // `Apa yang membuatmu berhenti sejenak dan merenung?`,
  // `Hari ini kamu belajar apa dari dirimu sendiri?`,
  // `Apa yang kamu rasakan saat bangun tidur tadi?`,
  // `Apa momen paling tenang hari ini?`,
  // `Apa warna yang kamu lihat terus hari ini?`,
  // `Kalau hari ini bisa dijadikan film, adegan apa yang paling menonjol?`,
  // `Ada hal yang buatmu teringat masa kecil?`,
  // `Siapa yang paling kamu pikirkan hari ini?`,
  // `Apa hal kecil yang kamu selesaikan dan bikin bangga?`,
  // `Apa satu kata yang menggambarkan harimu?`,
  // `Apa kejutan kecil yang terjadi hari ini?`,
  // `Apa yang kamu lewatkan hari ini tapi tidak menyesal?`,
  // `Apa yang membuatmu merasa "hidup" hari ini?`,
  // `Apakah kamu menemukan keindahan dalam hal biasa hari ini?`,
  // `Siapa yang kamu lihat hari ini tapi tak sempat menyapa?`,
  // `Hal bodoh apa yang terjadi tapi bikin kamu ketawa?`,
  // `Apa yang kamu harapkan terjadi, tapi tidak jadi?`,
  // `Kalau harimu diberi judul, apa judulnya?`,
  // `Apa hal terkecil yang membuatmu merasa nyaman?`,
  // `Apa keputusan kecil yang kamu ambil hari ini?`,
  // `Apakah kamu membantu seseorang hari ini?`,
  // `Apa isi pikiranmu saat sedang tidak melakukan apa-apa?`,
  // `Apa satu momen yang ingin kamu simpan selamanya?`,
  // `Apa yang kamu rasakan saat melihat langit hari ini?`,
  // `Apa hal tak terduga yang membuatmu tersenyum?`,
  // `Apakah kamu merasa didengarkan hari ini?`,
  // `Siapa yang kamu lihat diam-diam hari ini?`,
  // `Apa yang kamu lakukan untuk dirimu sendiri hari ini?`,
  // `Apa momen "oh iya!" hari ini?`,
  // `Hal apa yang hari ini terasa lebih mudah dari biasanya?`,
  // `Apa hal yang membuatmu lupa waktu hari ini?`,
  // `Apakah kamu merasa bangga pada dirimu hari ini?`,
  // `Apa sesuatu yang tidak kamu katakan, tapi ingin kamu ucapkan?`,
  // `Ada hal yang kamu tunda hari ini?`,
  // `Kalau ada satu foto dari hari ini, apa yang kamu ingin foto itu tangkap?`,
  // `Apa yang ingin kamu kirim sebagai pesan untuk dirimu 10 tahun ke depan dari hari ini?`,

  `What small thing was the most memorable today?`,
  `Who made you smile today?`,
  `What was the funniest moment today?`,
  `What new thing did you realize today?`,
  `What simple thing are you grateful for today?`,
  `If there's one thing you could relive from today, what would it be?`,
  `What's one event that made you think?`,
  `What did you see on the street that caught your attention?`,
  `What was the most enjoyable conversation today?`,
  `What sound or song filled your day?`,
  `What scent or food did you enjoy today?`,
  `What little thing made you feel at peace?`,
  `What small incident annoyed you but was funny?`,
  `Who did you meet today that left an impression?`,
  `What made you pause and reflect today?`,
  `What did you learn about yourself today?`,
  `How did you feel when you woke up this morning?`,
  `What was the calmest moment today?`,
  `What color did you keep noticing today?`,
  `If today were a movie, what scene would stand out the most?`,
  `Was there something that reminded you of childhood today?`,
  `Who did you think about the most today?`,
  `What small thing did you complete that made you proud?`,
  `What one word describes your day?`,
  `What little surprise happened today?`,
  `What did you miss out on today but don't regret?`,
  `What made you feel “alive” today?`,
  `Did you find beauty in something ordinary today?`,
  `Who did you see today but didn't get a chance to greet?`,
  `What silly thing happened that made you laugh?`,
  `What did you hope would happen, but didn't?`,
  `If your day had a title, what would it be?`,
  `What tiniest thing made you feel comfortable?`,
  `What small decision did you make today?`,
  `Did you help someone today?`,
  `What was on your mind when you weren't doing anything?`,
  `What's one moment you want to keep forever?`,
  `How did you feel when you looked at the sky today?`,
  `What unexpected thing made you smile?`,
  `Did you feel listened to today?`,
  `Who did you secretly look at today?`,
  `What did you do for yourself today?`,
  `What was your “oh right!” moment today?`,
  `What felt easier than usual today?`,
  `What made you lose track of time today?`,
  `Did you feel proud of yourself today?`,
  `What's something you didn't say but wanted to?`,
  `What did you postpone today?`,
  `If there was one photo from today, what would you want it to capture?`,
  `What message would you send to yourself 10 years from now about today?`,
]

export const getRandomPrompt = (array: string[]): string => { return array[Math.floor(Math.random() * array.length)] }

export const getRandomPrompts = () => { return { promptContent: getRandomPrompt(PROMPT) }}